version: '3.8'

services:
  exercise:
    build: .
    container_name: teamviewer_con
    image: 'teamviewer_img'
    ports:
      - "8000:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres-db
  postgres:
    image: postgres
    container_name: postgres_con
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres-db
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
volumes:
  postgres-data: {}